SET ANSI_NULLS on
set QUOTED_IDENTIFIER  ON
SELECT  TOP 20
	CONVERT(VARCHAR(10),CAST(CAST(Aces.dbo.STUDIES_TABLE.date -2 AS Datetime) AS Date)) AS Date,
	CONVERT(VARCHAR(30),Aces.dbo.PROCEDURES_TABLE.NAME) AS CASETYPE,
	CONVERT(VARCHAR(3),CHARINDEX('SMARTTOUCH',Cath.names)) AS ST,
	CONVERT(VARCHAR(3),CHARINDEX('PENTARAY',Cath.names)) AS PENTA,
	CONVERT(VARCHAR(3),CHARINDEX('VIZIGO',Cath.names)) AS VIZIGO,
	CONVERT(VARCHAR(3),CHARINDEX('DECANAV',Cath.names)) AS DECANAV,
	CONVERT(VARCHAR(3),CHARINDEX('LASSO',Cath.names)) AS LASSO,
	TODOS.MAP_IDX,
	TODOS.TODOS AS POINTS,
	100*CONTACT.CONTACT/TODOS.TODOS AS CONTACTO
FROM 	Aces.dbo.STUDIES_TABLE
LEFT JOIN    Aces.dbo.SETUP_TABLE
ON      Aces.dbo.SETUP_TABLE.SETUP_IDX = Aces.dbo.STUDIES_TABLE.SETUP_IDX
LEFT JOIN
(
SELECT   Aces.dbo.POINTS_TABLE.MAP_IDX AS MAP_IDX,
	 Aces.dbo.MAPS_TABLE.STUDY_IDX AS STUDY_IDX,
         COUNT(Aces.dbo.POINTS_TABLE.POINT_IDX) AS TODOS
FROM     Aces.dbo.MAPS_TABLE,
	 Aces.dbo.POINTS_TABLE
WHERE    Aces.dbo.MAPS_TABLE.MAP_IDX = Aces.dbo.POINTS_TABLE.MAP_IDX
AND 	 Aces.dbo.POINTS_TABLE.DELETED = 0
group BY Aces.dbo.POINTS_TABLE.MAP_IDX,
	 Aces.dbo.MAPS_TABLE.STUDY_IDX
) AS TODOS
ON 	Aces.dbo.STUDIES_TABLE.STUDY_IDX = TODOS.STUDY_IDX
LEFT JOIN
(
SELECT 	Aces.dbo.POINTS_TABLE.MAP_IDX AS MAP_IDX,
       	COUNT(Aces.dbo.POINTS_TABLE.POINT_IDX) AS CONTACT
FROM   	Aces.dbo.MAPS_TABLE,
	Aces.dbo.POINTS_TABLE
WHERE   Aces.dbo.MAPS_TABLE.MAP_IDX = Aces.dbo.POINTS_TABLE.MAP_IDX
AND 	Aces.dbo.POINTS_TABLE.DELETED = 0
AND     Aces.dbo.POINTS_TABLE.TOUCH_STATUS > 0
group BY Aces.dbo.POINTS_TABLE.MAP_IDX
) AS CONTACT
ON CONTACT.MAP_IDX = TODOS.MAP_IDX
LEFT JOIN
(
SELECT DISTINCT(Aces.dbo.STUDIES_TABLE.STUDY_IDX), CONFIG_MAIN_TABLE.PROCEDURE_IDX AS ptype,
			STUFF((
          			SELECT ',' + Aces.dbo.CONFIG_CONNECTOR_TABLE.CATHETER_NAME
          			FROM  Aces.dbo.CONFIG_CONNECTOR_TABLE
          			WHERE Aces.dbo.CONFIG_MAIN_TABLE.CONFIG_IDX = Aces.dbo.CONFIG_CONNECTOR_TABLE.CONFIG_IDX
          			AND Aces.dbo.CONFIG_CONNECTOR_TABLE.IS_IN_CONNECTOR_SETUP =1
          			FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'
						 ), 1, 1, '') as names
FROM Aces.dbo.STUDIES_TABLE,
     Aces.dbo.CONFIG_MAIN_TABLE,
     Aces.dbo.CONFIG_CONNECTOR_TABLE
WHERE
 	Aces.dbo.STUDIES_TABLE.SETUP_IDX = Aces.dbo.CONFIG_MAIN_TABLE.SETUP_IDX
AND
 	Aces.dbo.CONFIG_MAIN_TABLE.CONFIG_IDX = Aces.dbo.CONFIG_CONNECTOR_TABLE.CONFIG_IDX
) AS Cath
ON Cath.STUDY_IDX = Aces.dbo.STUDIES_TABLE.STUDY_IDX
LEFT JOIN  Aces.dbo.PROCEDURES_TABLE
on  Aces.dbo.PROCEDURES_TABLE.PROCEDURE_IDX = Cath.ptype
ORDER BY DATE DESC